### ISSUE TITLE
Dúvida sobre o exercício 3

### ISSUE THREAD

**Issue by RaquelrCruz** [mathiasbrito/CET836#1]
Boa tarde professor
Estou com uma dúvida no exercício 3. Eu queria colocar para que o leitor do programa também digitasse seu nome para aparecer lá na impressão, porém quando eu digito o nome e pulo uma linha para continuar a impressão acaba dando errado. Aí estou sem como saber como consertar esse erro.

**Comment by mathiasbrito** [comment]
Você poderia colar o seu código aqui? coloca ele entre três crases, tanto no começo como depois dele. Pode ser por causa de espaços no nome, você está colocando espaços? caso sim, coloca sem espaços e veja se funciona...

**Comment by mathiasbrito** [comment]
Dá uma olhada nesse link https://wiki.portugal-a-programar.pt/dev_geral:c:scanfparastrings

**Comment by RaquelrCruz** [comment]
Conseguir achar o erro. Mas obrigada msm assim

**Comment by RaquelrCruz** [comment]
Era a falta do espaço mesmo

**Comment by mathiasbrito** [comment]
era a falta ou o uso de espaços? como ficou o seu marcador? %s puro?
