### ISSUE TITLE
soma de matrizes 

### ISSUE THREAD

**Issue by Thayla833** [mathiasbrito/CET836#5]
professor esta certo o código, e o formato que ele é impresso na tela?

#include <stdio.h>

 //A soma de duas matrizes e dada pela soma das céluas de mesma posição em duas ou mais matrizes. Dada uma matriz 2x2 A = {{2, 2}, {3, 5}} e a matriz 2x2 B = {{9, 3}, {1, 4}} a soma dessas matrizes resultara em R = {{11, 5}, {4, 9}}

int main(void) {

int matriz1[2][2] =  {{2, 2}, {3, 5}};
int matriz2[2][2] =  {{9, 3}, {1, 4}};
int soma;
int i;
int j;

for(i=0; i<2;i++){
for(j=0;j<2;j++){
  soma= (matriz1[i][j] + matriz2[i][j]);

printf("a soma das duas matrizes é:" "%d\n",soma);
}

}

  return 0;
}

**Comment by mathiasbrito** [comment]
Quase lá, só que soma é uma matriz também é a soma deve ser armazenada na mesma célula [i][j] do vetor soma... na impressão você imprime soma[i][j] dentro dos dois fors...
