### ISSUE TITLE
PROVA

### ISSUE THREAD

**Issue by Thayla833** [mathiasbrito/CET836#6]
PROFESSOR BOA NOITE, COMO NÃO TEVE AULA NESSA SEXTA, A AULA DE REVISÃO E DUVIDAS DO ULTIMO ASSUNTO QUE O SENHOR PASSOU VAI SER NA SEMANA QUE VEM? O SENHOR VAI ADIAR A PROVA MAIS UMA SEMANA?

**Comment by mathiasbrito** [comment]
Sim, irei adiar mais uma semana.
